name: The 806 Coffee + Lounge
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4291737
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
title: The 806 Coffee + Lounge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#CDCDCD'
    - '#010099'
    - '#7F7F7F'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
